-- Esquema de negocio para el Banco XYZ (compatible con H2 y PostgreSQL)
-- Se ejecuta automaticamente al iniciar la aplicacion (spring.sql.init.mode=always)

CREATE TABLE IF NOT EXISTS daily_transaction_report (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id    VARCHAR(50)    NOT NULL,
    account_id        VARCHAR(50)    NOT NULL,
    transaction_date  DATE           NOT NULL,
    type              VARCHAR(20)    NOT NULL,
    amount            DECIMAL(15,2)  NOT NULL,
    currency          VARCHAR(10)    NOT NULL,
    status             VARCHAR(20)    NOT NULL,
    is_anomaly        BOOLEAN        NOT NULL DEFAULT FALSE,
    anomaly_reason    VARCHAR(200),
    processed_at      TIMESTAMP      NOT NULL
);

CREATE TABLE IF NOT EXISTS account_balance (
    account_id            VARCHAR(50)    PRIMARY KEY,
    account_type          VARCHAR(20)    NOT NULL,
    balance                DECIMAL(15,2)  NOT NULL,
    interest_rate          DECIMAL(6,4)   NOT NULL,
    interest_applied       DECIMAL(15,2),
    previous_balance      DECIMAL(15,2),
    last_interest_applied TIMESTAMP,
    updated_at             TIMESTAMP      NOT NULL
);

CREATE TABLE IF NOT EXISTS annual_statement (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id          VARCHAR(50)    NOT NULL,
    holder_name         VARCHAR(120)   NOT NULL,
    statement_year      INT            NOT NULL,
    opening_balance     DECIMAL(15,2)  NOT NULL,
    total_deposits      DECIMAL(15,2)  NOT NULL,
    total_withdrawals   DECIMAL(15,2)  NOT NULL,
    total_interest      DECIMAL(15,2)  NOT NULL,
    closing_balance     DECIMAL(15,2)  NOT NULL,
    is_consistent       BOOLEAN        NOT NULL,
    difference_amount   DECIMAL(15,2)  NOT NULL,
    generated_at        TIMESTAMP      NOT NULL
);

CREATE TABLE IF NOT EXISTS batch_error_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_name      VARCHAR(80)    NOT NULL,
    raw_item      VARCHAR(500),
    error_type    VARCHAR(150),
    error_message VARCHAR(500),
    logged_at     TIMESTAMP      NOT NULL
);
